# Generated by Django 3.1.6 on 2021-02-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chice',
            new_name='choice',
        ),
    ]
